puts "Students in the September 2014 Makers Academy cohort"
puts "-----------------"
puts "Bernard - bmordan"
puts "Nicole - NicolePell"
puts "Yvette - yvettecook"
puts "Elena - elenagarrone"
puts "Fadie - fadieh"
puts "Tim - Scully87"
puts "Ella - EllaNancyFay"
puts "Andrew - andrewhercules"
puts "Camilla - camillavk"
puts "Sandrine - MadameSardine"
puts "Pablo - galicians"
puts "Rachel - SBLLB"
puts "Steve - HatStephens"